# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField()),
                ('version', models.IntegerField()),
            ],
        ),
    ]
