# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressentry',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addressentry',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
